-- Part 03 initial schema. Reviewed and approved (ERD + DDL) before any entity was written --
-- see CLAUDE.md "Schema additions needed before Part 03" and PRD.md section 9.2.
--
-- Naming: "orders" not "order" (ORDER is a reserved word in PostgreSQL); "sent_at" not
-- "timestamp" (avoids the type-name/column-name collision risk). All foreign keys default to
-- ON DELETE RESTRICT (no clause) except order_extras, which cascades since extras have no
-- independent existence -- the same ownership semantics as the @ElementCollection they map from.

CREATE TABLE user_accounts (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(255) NOT NULL,
    role             VARCHAR(20)  NOT NULL,
    fulfilled_orders BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT chk_user_role CHECK (role IN ('CUSTOMER','BARISTA','MANAGER')),
    CONSTRAINT chk_user_fulfilled_orders_nonneg CHECK (fulfilled_orders >= 0)
);
-- CustomerEntity is merged into this table (fulfilled_orders lives here, meaningful only for
-- role = CUSTOMER rows) rather than kept as a second, disconnected identity table -- see the
-- Step 1 schema proposal for the full reasoning. No unique constraint on name: this project has
-- no login/auth system (PRD section 4), so there is no "username" to make unique.

CREATE TABLE orders (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id           BIGINT        NOT NULL CONSTRAINT fk_orders_customer REFERENCES user_accounts(id),
    base_coffee_type      VARCHAR(20)   NOT NULL,
    status                VARCHAR(20)   NOT NULL,
    applied_loyalty_tier  VARCHAR(20)   NOT NULL,
    price_base            NUMERIC(10,2) NOT NULL,
    price_extras          NUMERIC(10,2) NOT NULL,
    price_discount        NUMERIC(10,2) NOT NULL,
    price_total           NUMERIC(10,2) NOT NULL,
    placed_at             TIMESTAMPTZ   NOT NULL,
    updated_at            TIMESTAMPTZ   NOT NULL,
    version               INTEGER       NOT NULL DEFAULT 0,
    CONSTRAINT chk_order_status CHECK (status IN ('PLACED','PREPARING','READY','FULFILLED','CANCELLED')),
    CONSTRAINT chk_order_coffee_type CHECK (base_coffee_type IN ('ESPRESSO','CAPPUCCINO','LATTE')),
    CONSTRAINT chk_order_tier CHECK (applied_loyalty_tier IN ('REGULAR','SILVER','GOLD')),
    CONSTRAINT chk_order_price_base_nonneg CHECK (price_base >= 0),
    CONSTRAINT chk_order_price_extras_nonneg CHECK (price_extras >= 0),
    CONSTRAINT chk_order_price_discount_nonneg CHECK (price_discount >= 0),
    CONSTRAINT chk_order_price_total_nonneg CHECK (price_total >= 0),
    CONSTRAINT chk_order_price_consistent CHECK (price_total = price_base + price_extras - price_discount)
);
CREATE INDEX idx_orders_customer_id ON orders(customer_id);
-- Restart recovery (Part 03 Step 3): after a process restart, OrderQueue (in-memory) is empty
-- but PLACED/PREPARING rows may still exist from before the crash. This index serves the
-- ApplicationReadyEvent recovery query that finds them.
CREATE INDEX idx_orders_status ON orders(status);
-- price_total = price_base + price_extras - price_discount is computed once, at scale 2, with a
-- fixed RoundingMode (HALF_UP), by PriceBreakdown before an OrderEntity is ever built -- see
-- OrderEntity's constructor and OrderRepositoryTest.roundingBoundaryNeverViolatesPriceConsistency()
-- for the boundary-rounding proof this check can never reject a legitimately-built order.

CREATE TABLE order_extras (
    order_id    BIGINT      NOT NULL CONSTRAINT fk_order_extras_order REFERENCES orders(id) ON DELETE CASCADE,
    extra_index INTEGER     NOT NULL,
    extra_type  VARCHAR(20) NOT NULL,
    PRIMARY KEY (order_id, extra_index),
    CONSTRAINT chk_order_extra_type CHECK (extra_type IN ('MILK','SUGAR','WHIPPED_CREAM'))
);

CREATE TABLE payments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT        NOT NULL CONSTRAINT fk_payments_order REFERENCES orders(id),
    provider   VARCHAR(20)   NOT NULL,
    amount     NUMERIC(10,2) NOT NULL,
    status     VARCHAR(20)   NOT NULL,
    detail     VARCHAR(255),
    created_at TIMESTAMPTZ   NOT NULL,
    updated_at TIMESTAMPTZ   NOT NULL,
    CONSTRAINT uq_payments_order_id UNIQUE (order_id),
    CONSTRAINT chk_payment_provider CHECK (provider IN ('PAYPAL','STRIPE','CASH')),
    CONSTRAINT chk_payment_status CHECK (status IN ('PENDING','PAID','FAILED')),
    CONSTRAINT chk_payment_amount_positive CHECK (amount > 0)
);
-- One row per order (UNIQUE(order_id), no retry-with-a-new-row modeling). Inserted once, after
-- the gateway responds, with status PAID or FAILED directly -- PENDING stays a valid enum value
-- for schema completeness but Part 03's code path never produces it. Application code enforces
-- amount = orders.price_total at write time (a CHECK constraint can't reference another table).

CREATE TABLE order_status_history (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT      NOT NULL CONSTRAINT fk_order_status_history_order REFERENCES orders(id),
    from_status VARCHAR(20),
    to_status   VARCHAR(20) NOT NULL,
    changed_at  TIMESTAMPTZ NOT NULL,
    changed_by  BIGINT      CONSTRAINT fk_order_status_history_changed_by REFERENCES user_accounts(id),
    CONSTRAINT chk_hist_from_status CHECK (from_status IN ('PLACED','PREPARING','READY','FULFILLED','CANCELLED')),
    CONSTRAINT chk_hist_to_status CHECK (to_status IN ('PLACED','PREPARING','READY','FULFILLED','CANCELLED'))
);
CREATE INDEX idx_order_status_history_order_changed ON order_status_history(order_id, changed_at);
-- changed_by: nullable FK to user_accounts. NULL means an automated/system transition (the async
-- consumer loops are threads, not user accounts). When set, it must be a user whose role is
-- BARISTA -- a plain FK cannot check the referenced row's role, so that rule is enforced in the
-- application layer (Part 03 Step 4), not here. Order-status transition *legality*
-- (PLACED -> PREPARING -> ...) also stays app-only (OrderStatus.canTransitionTo) rather than
-- being duplicated as a CHECK constraint -- two places that must never drift, one much harder to
-- change safely.

CREATE TABLE chat_sessions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT      NOT NULL CONSTRAINT fk_chat_sessions_customer REFERENCES user_accounts(id),
    barista_id  BIGINT      CONSTRAINT fk_chat_sessions_barista REFERENCES user_accounts(id),
    status      VARCHAR(20) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_chat_session_status CHECK (status IN ('WAITING','ACTIVE','INACTIVE'))
);
CREATE INDEX idx_chat_sessions_customer_id ON chat_sessions(customer_id);
-- Restart recovery (Part 03 Step 5): BaristaQueue is in-memory FIFO matching state; after a
-- restart it has forgotten every WAITING session. This index serves the startup recovery query.
CREATE INDEX idx_chat_sessions_status ON chat_sessions(status);
-- At most one non-INACTIVE session per customer, DB-enforced defense-in-depth alongside the
-- app-level check (ChatService.startChat()).
CREATE UNIQUE INDEX uq_chat_sessions_active_customer ON chat_sessions(customer_id) WHERE status <> 'INACTIVE';
-- No index on barista_id yet: added when a query that actually filters by it exists (Part 03
-- Step 5/6, e.g. "this barista's active sessions"), not speculatively now.

CREATE TABLE chat_messages (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT       NOT NULL CONSTRAINT fk_chat_messages_session REFERENCES chat_sessions(id),
    type        VARCHAR(20)  NOT NULL,
    sender_id   BIGINT       CONSTRAINT fk_chat_messages_sender REFERENCES user_accounts(id),
    sender_name VARCHAR(255) NOT NULL,
    content     TEXT         NOT NULL,
    sent_at     TIMESTAMPTZ  NOT NULL,
    order_id    BIGINT       CONSTRAINT fk_chat_messages_order REFERENCES orders(id),
    CONSTRAINT chk_chat_message_type CHECK (type IN ('CHAT_MESSAGE','SYSTEM_MESSAGE')),
    CONSTRAINT chk_chat_message_content_not_blank CHECK (btrim(content) <> ''),
    CONSTRAINT chk_chat_message_content_length CHECK (char_length(content) <= 2000)
);
CREATE INDEX idx_chat_messages_session_sent ON chat_messages(session_id, sent_at);
-- sender_id is nullable (NULL = a SYSTEM_MESSAGE, no fake "System" user row needed). sender_name
-- is kept as its own persisted column even though it's derivable from the sender_id FK for
-- non-system messages: chat messages are historical records, and a later display-name change
-- shouldn't rewrite what an old message shows. No index on sender_id (per review) or order_id
-- (no query filters by it yet).
